### ISSUE TITLE
보호소 목록 페이지

### ISSUE THREAD

**Issue by bluel00** [PEC-FE/pet-save#4]
- [x] entity
- [x] 페이지에 Shelters를 보여준다

일단 여기까지하고 리팩터링6

**Comment by bluel00** [comment]
무엇을 보여줄지? (entity)
- Shelters

- 전체 결과수
- 페이지 번호
- 한 페이지 결과수

- rowItem 보호소 정보
	- 동물보호센터명
	- 동물보호센터유형 (ex.동물병원)
	- 구조대상동물
	- 소재지도로명주소
	- 전화번호
	- 운영 시간 정보
	

이 데이터 중 본질이 뭐지? (이 페이지에서, 사용자 관점에서)
주소, 센터유형, 구조대상동물, 전화번호를 보고 직접 연락하거나 상세페이지로 진입

목록 페이지의 관심사는
- 전체 항목은 몇개인지?
- 페이지 정보
	- 전체 페이지
	- 현재 페이지
- 한 페이지에 몇 줄을 보여줄지


도메인은 
- Shelters
    - Shelter
    - Pagenation

**Comment by boaz-hwang** [comment]
> 무엇을 보여줄지? (entity)
> 
> * Shelters
> * 전체 결과수
> * 페이지 번호
> * 한 페이지 결과수
> * rowItem 보호소 정보
>   
>   * 동물보호센터명
>   * 동물보호센터유형 (ex.동물병원)
>   * 구조대상동물
>   * 소재지도로명주소
>   * 전화번호
>   * 운영 시간 정보
> 
> 이 데이터 중 본질이 뭐지? (이 페이지에서, 사용자 관점에서) 주소, 센터유형, 구조대상동물, 전화번호를 보고 직접 연락하거나 상세페이지로 진입
> 
> 목록 페이지의 관심사는
> 
> * 전체 항목은 몇개인지?
> * 페이지 정보
>   
>   * 전체 페이지
>   * 현재 페이지
> * 한 페이지에 몇 줄을 보여줄지
> 
> 도메인은
> 
> * Shelters
>   
>   * Shelter
>   * Pagenation

목록 페이지 interface 는 다른 도메인에서도 함께 사용할 수 있을것 같아서요. 
이런 부분을 고려해서 코드를 구현하면 좋을것 같은데, 이 부분에 관한 자세한 의견은 PR 리뷰에 남기겠습니다 🙏
